### ISSUE TITLE
NameError: uninitialized constant Sidekiq::Component (NameError)

### ISSUE THREAD

**Issue by kerzhner** [iMacTia/sidekiq-logstash#37] opened 2024-08-12 22:22 UTC
On upgrading Sidekiq from 7.2.4 to 7.3.0, we started seeing an error similar to https://github.com/sidekiq/sidekiq/issues/6395. Sidekiq author @mperham states that this is a [sidekiq-logstash issue](https://github.com/sidekiq/sidekiq/issues/6395#issuecomment-2276620626). Any chance one of the maintainers of this gem could take a look at this issue?

**Comment by kerzhner** [comment] 2024-08-12 22:25
Our stack trace is:

```
NameError: uninitialized constant Sidekiq::Component (NameError)

    include Sidekiq::Component
                   ^^^^^^^^^^^
Did you mean?  Complex
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/job_logger.rb:5:in `<class:JobLogger>'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/job_logger.rb:4:in `<module:Sidekiq>'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/job_logger.rb:3:in `<main>'
.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.15/lib/zeitwerk/kernel.rb:34:in `require'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/sidekiq-logstash-3.0.0/lib/sidekiq/logstash_job_logger.rb:3:in `<main>'
.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.15/lib/zeitwerk/kernel.rb:34:in `require'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/sidekiq-logstash-3.0.0/lib/sidekiq/logstash.rb:7:in `<main>'
<internal:.rbenv/versions/3.3.3/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:.rbenv/versions/3.3.3/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.15/lib/zeitwerk/kernel.rb:34:in `require'
.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundler/runtime.rb:73:in `rescue in block in require'
.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundler/runtime.rb:51:in `block in require'
.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundler/runtime.rb:44:in `each'
.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundler/runtime.rb:44:in `require'
.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundler.rb:207:in `require'
app/config/application.rb:15:in `<main>'
.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
app/Rakefile:11:in `<main>'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/rake-13.2.1/lib/rake/rake_module.rb:29:in `load'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/rake-13.2.1/lib/rake/rake_module.rb:29:in `load_rakefile'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:740:in `raw_load_rakefile'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:126:in `block in load_rakefile'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:214:in `standard_exception_handling'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:125:in `load_rakefile'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/railties-7.1.3.3/lib/rails/commands/rake/rake_command.rb:43:in `block in with_rake'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/rake-13.2.1/lib/rake/rake_module.rb:59:in `with_application'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/railties-7.1.3.3/lib/rails/commands/rake/rake_command.rb:41:in `with_rake'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/railties-7.1.3.3/lib/rails/commands/rake/rake_command.rb:20:in `perform'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/railties-7.1.3.3/lib/rails/command.rb:156:in `invoke_rake'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/railties-7.1.3.3/lib/rails/command.rb:73:in `block in invoke'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/railties-7.1.3.3/lib/rails/command.rb:149:in `with_argv'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/railties-7.1.3.3/lib/rails/command.rb:69:in `invoke'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/railties-7.1.3.3/lib/rails/commands.rb:18:in `<main>'
.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
bin/rails:9:in `<main>'

Caused by:
LoadError: cannot load such file -- sidekiq-logstash (LoadError)
<internal:.rbenv/versions/3.3.3/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:.rbenv/versions/3.3.3/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.15/lib/zeitwerk/kernel.rb:34:in `require'
.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundler/runtime.rb:60:in `block (2 levels) in require'
.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundler/runtime.rb:55:in `each'
.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundler/runtime.rb:55:in `block in require'
.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundler/runtime.rb:44:in `each'
.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundler/runtime.rb:44:in `require'
.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundler.rb:207:in `require'
app/config/application.rb:15:in `<main>'
.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
app/Rakefile:11:in `<main>'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/rake-13.2.1/lib/rake/rake_module.rb:29:in `load'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/rake-13.2.1/lib/rake/rake_module.rb:29:in `load_rakefile'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:740:in `raw_load_rakefile'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:126:in `block in load_rakefile'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:214:in `standard_exception_handling'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:125:in `load_rakefile'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/railties-7.1.3.3/lib/rails/commands/rake/rake_command.rb:43:in `block in with_rake'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/rake-13.2.1/lib/rake/rake_module.rb:59:in `with_application'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/railties-7.1.3.3/lib/rails/commands/rake/rake_command.rb:41:in `with_rake'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/railties-7.1.3.3/lib/rails/commands/rake/rake_command.rb:20:in `perform'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/railties-7.1.3.3/lib/rails/command.rb:156:in `invoke_rake'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/railties-7.1.3.3/lib/rails/command.rb:73:in `block in invoke'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/railties-7.1.3.3/lib/rails/command.rb:149:in `with_argv'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/railties-7.1.3.3/lib/rails/command.rb:69:in `invoke'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/railties-7.1.3.3/lib/rails/commands.rb:18:in `<main>'
.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
bin/rails:9:in `<main>'
```

**Comment by iMacTia** [comment] 2024-08-30 10:18
Hi @kerzhner, sorry I was out for summer holidays. Will take a look

**Comment by iMacTia** [comment] 2024-08-30 11:07
@kerzhner this should be fixed [here](https://github.com/iMacTia/sidekiq-logstash/commit/43e9bb8b3a235e1f97901312e90b3cb1e2e69ede#diff-e62b9c5d92fc101ee18bb70fe7ac064b59385dcc72c8404329760a24e864f8a3), any chance you could try using `master` in your project and let me know if the issue is gone for you?

**Closed** 2024-09-03 15:27 UTC

**Comment by iMacTia** [comment] 2024-09-03 15:32
Just release [v3.1.0](https://rubygems.org/gems/sidekiq-logstash/versions/3.1.0) with the fix 👍
